[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts', 'v3-periphery/=lib/v3-periphery/contracts', '@uniswap/v3-core=lib/v3-core']

# See more config options https://github.com/gakonst/foundry/tree/master/config
